#include "mlir/IR/Builders.h"

#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/XilinxPrimitives/XilinxPrimitivesOps.h"

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/XilinxPrimitives/XilinxPrimitives.cpp.inc"
